import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import Banner from "@/components/layout/banner";
import { ToastProvider } from "@/components/ui/toast";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased `}
      >
        <ToastProvider>
        <Banner/>
        <Header />
        {children}
        <Footer />
        </ToastProvider>
       
      </body>
    </html>
  );
}
